name: Build Windows Setup
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Build optimized app folder
        run: pyinstaller --noconfirm --clean --windowed --onedir --name MessengerDesk --collect-all PySide6.QtWebEngineCore --collect-all PySide6.QtWebEngineWidgets main.py
      - name: Install Inno Setup
        shell: powershell
        run: choco install innosetup --no-progress -y
      - name: Build Setup
        shell: powershell
        run: '& "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer.iss'
      - uses: actions/upload-artifact@v4
        with:
          name: MessengerDesk-Setup
          path: installer/MessengerDesk-Setup.exe
